### ISSUE TITLE
not an issue but need help.

### ISSUE THREAD

**Issue by jigoop1** [ibid-11962/reddit-post-scheduler#1]
hi, 
thanks for this script.
i tried to submit the post as :
`submission=reddit.subreddit(sub).submit(title, selftext = text, send_replies = not (dontnotify))`
work but when i tried to submit the post  with flair id and text as :
`submission=reddit.subreddit(sub).submit(title, selftext = text, flair_id = flairid, flair_text = flairtext, send_replies = not (dontnotify))`
did not work and give error 400,so my question is ,one have to be moderator in order to submit the post with flairid  and flartext?

**Comment by ibid-11962** [comment]
flairid and flairtext depend on the subreddit I think. They can be set to have all are some of the flairs (or just flair text) require moderation privileges to use.

**Comment by jigoop1** [comment]
thanks for responce,
btw here is the flair templet i got from subreddit:
`for flair in reddit.subreddit(SUB).flair.templates:` as
flair = {'allowable_content': 'all', 'text': 'Enthusiast', 'text_color': 'dark', 'mod_only': False, 'background_color': '', 'id': 'csa9bf3a-723e-11e6-875b-0r569e554ebb', 'css_class': '', 'max_emojis': 10, 'richtext': [], 'text_editable': True, 'override_css': False, 'type': 'text'}
do i still need moderation privileges to use? since text_editable. btw for yr info i do not have moderation privileges on that sub.

**Comment by ibid-11962** [comment]
Honestly I have no idea. I've never really tested the flairing stuff on subreddits I don't moderate. Can you try manually assigning that flair through the website itself?

**Comment by jigoop1** [comment]
yeah sure, I don't moderate either but try to post with praw, thanks for yr help.
