### ISSUE TITLE
How to add submit_gallery function?

### ISSUE THREAD

**Issue by GreenArmadilloette** [ibid-11962/reddit-post-scheduler#2]
Hi, this is a fantastic script!
I'm not very good at programming, but I was just wondering how I could add the [sumbit_gallery](https://praw.readthedocs.io/en/latest/code_overview/models/subreddit.html#praw.models.Subreddit.submit_gallery) function to this.

**Comment by ibid-11962** [comment]
So I wrote this at a time before reddit had added that feature. It looks like the only new argument the sumbit_gallery function needs is `images`, but PRAW has that as an object and if I was still coding this I might have added some extra code to try making the input more flat like the other commands. 

But if you're okay with a more complicated input, all that you'd really have to change is:

- Modify the three lines in the main loop to pass an extra `images` argument to `submitPost`.
- Modify `submitPost` to accept an extra `images` argument.
- Modify the logic in `submitPost` to use the `submit_gallery` when `images` is not None.

All of those you should be able to more or less base off of the existing code, and should probably be possible with some trial and error even if you aren't sure what all the code is doing.

Hope that helps.
