### ISSUE TITLE
Setting reddit.validate_on_submit to True

### ISSUE THREAD

**Issue by mykahveli** [ibid-11962/reddit-post-scheduler#3]
Hello.

I'm getting the following error:

`postscheduler.py:34: DeprecationWarning: Reddit will check for validation on all posts around May-June 2020. It is recommended to check for validation by setting reddit.validate_on_submit to True.`

Also, the log says:

`Error posting submission -- received 401 HTTP response. Error posting comment -- local variable 'submission' referenced before assignment
`

Thank you.

**Comment by ibid-11962** [comment]
Which version of praw are you using?

Which subreddit are you trying to submit to, and does your post meet the posting requirements of that subreddit?

**Comment by mykahveli** [comment]
I'm really sorry to bother. I had the wrong secret.

In the meantime, the log show this malformed URL: `Posted --  https://reddit.comhttps://www.reddit.com/r/sandboxtest/comments/lquuvk/titletext/`. Probably the problem is with `def tolink(permalink)`?

Finally, it is possible to include the time, like 14:30 GMT, to `"date": "2,23"`?

Thank you.

**Comment by ibid-11962** [comment]
I think the logged links should now be fixed.

This app is designed to take advantage of pythonanywhere's free tier where you can schedule a script to run daily at a set time, so the time of every post would have to be the time that the script runs. (It runs once per day at the scheduled time, checks if anything should be posted, and then quits.) Adding custom times for each post would require being able to run the script more frequently or having it continuously running in the background. They're outside the current scope of this project.
