### ISSUE TITLE
Schedule comments on non-existent post

### ISSUE THREAD

**Issue by Ruriko** [ibid-11962/reddit-post-scheduler#4]
Is it possible to schedule comments to posts that haven't been made yet? like I set to schedule to make a new post and then post a comment right after

**Comment by GreenArmadilloette** [comment]
Yes, it's this part of the code

posts = [

#---------------------#
{"sub": "subredditname",
"title": "titletext",
"text": "bodytext",
"commenttext": "commenttext",
"date": "8,11"},

**Comment by ibid-11962** [comment]
Yes, as @GreenArmadilloette said, you just include `"commenttext": "text of the comment"` to have a comment post itself under the new post. You can also use `"lockcomment": True`, `"distinguishcomment": True`, and/or `"stickycomment": True` to apply moderator effects to that comment.
