### ISSUE TITLE
How to post on hours?

### ISSUE THREAD

**Issue by kingchenc** [ibid-11962/reddit-post-scheduler#9]
Hi,

how can i change the code that the bot schedule at M/D/H and not only at M/D?

maybe anyone can help me :)

**Comment by ibid-11962** [comment]
This code was designed for a bot that is scheduled to run once a day, at the same time every day. (Which is possible with PythonAnywhere's free tier.) This of course assumes that you'd want all of your posts to be made at the same time of day every day.
